#include <cstdio>

int main()
{
	char s[250] = "UDRUURLLLDLLLUUULDDRDDDLDUUUUUURURRLUUUUUUUUUUUUUUUURRUURUUULLLLUUUURLLLLURUUUUURIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP\0";
	printf("%s\n", s);
	return 0;
}